#!/bin/sh
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

export PS1="\[\033[1;34m\]\! \[\033[0m\]\[\033[1;35m\]\u\[\033[0m\]:\[\033[1;35m\]\W\[\033[0m\]$ "

export SSL_CERT_FILE=/Users/hdicks001c/.certs/cacert.pem

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

gco_theirs() {
  git checkout --theirs -- $1
}

gco_ours() {
  git checkout --ours -- $1
}

ga() {
  git add $1
}

gerpshFeature() {
  git push origin HEAD:refs/for/feature/$1
}

togVim() {
  if [ -f ~/.vimrc ];
  then
    mv ~/.vimrc ~/vimrc
  else
    mv ~/vimrc ~/.vimrc
  fi
}

alias scuts='cat ~/.bash_profile'
alias unvim='mv ~/.vimrc ~/vimrc'
alias revim='mv ~/vimrc ~/.vimrc'
alias gogo='cd $GOPATH/src/github.com/hdicksonjr'
alias cdh='cd ~/'
alias sd='cd ~/sites/'
alias sic='cd ~/sites/TeamCharlie/si-components'
alias gd='git diff'
alias gdc='git diff --cached'
alias gds='git diff --stat'
alias gp='git pull'
alias grase='git rebase'
alias gsp='git stash&&git pull'
alias gb='git branch'
alias gco='git checkout'
alias gf='git fetch'
alias gca='git commit --amend'
alias gstat='git status'
alias gerpsh='git push origin HEAD:refs/for/master'
alias ghreset='git reset  --hard origin/master'

# completely replace local branch with master.
alias gtotalreplace='git fetch origin && git reset --hard origin/master'

export NVM_DIR="/Users/hdicks001c/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
